v1.5.2 release based on SVN rev 7501

diff --git a/model/tests/hd-us/closed/run_closed b/model/tests/hd-us/closed/run_closed
--- a/model/tests/hd-us/closed/run_closed
+++ b/model/tests/hd-us/closed/run_closed
@@ -1,42 +1,47 @@
-#!/bin/csh -f
+#!/bin/csh -ef
+
+# Set relative path to compas executable
+set COMPAS='../../../hd-us/compas'
+set SHOC='../../../hd/shoc'
 
 echo "Testing SHOC..."
-rm closed.nc
-rm out1.nc
+rm -f closed.nc || true
+rm -f out1.nc || true
 
-../shoc -g closed.prm closed.nc
-
-../shoc -p closed.prm
-
+if (-f $SHOC) then
+    $SHOC -g closed.prm closed.nc
+    $SHOC -p closed.prm
+else
+    echo "SHOC not found, skipping ..."
+endif
+    
 echo "DONE"
 
 echo "Testing COMPAS quad..."
-rm closed_quad.nc
-rm s_closed_quad.nc
-rm out1_quad.nc
-rm pt.nc
+rm -f closed_quad.nc || true
+rm -f s_closed_quad.nc || true
+rm -f out1_quad.nc || true
+rm -f pt.nc || true
 
-../compas -g closed_quad.prm closed_quad.nc
-
-../compas -p closed_quad.prm
+$COMPAS -g closed_quad.prm closed_quad.nc
+$COMPAS -p closed_quad.prm
 
 echo "DONE"
 
 echo "Testing COMPAS quad 5 window..."
-rm out1_quad5w.nc
-
-../compas -p closed_quad5w.prm
+rm -f out1_quad5w.nc || true
+$COMPAS -p closed_quad5w.prm
 
 echo "DONE"
 
 echo "Testing COMPAS hex..."
-rm closed_hex.nc
-rm out1_hex.nc
+rm -f closed_hex.nc || true
+rm -f out1_hex.nc || true
 
-../compas -g closed_hex.prm closed_hex.nc
-
-../compas -p closed_hex.prm
+$COMPAS -g closed_hex.prm closed_hex.nc
+$COMPAS -p closed_hex.prm
 
 echo "DONE"
+
 
 
diff --git a/model/tests/hd-us/run_tests b/model/tests/hd-us/run_tests
--- a/model/tests/hd-us/run_tests
+++ b/model/tests/hd-us/run_tests
@@ -1,7 +1,64 @@
-#!/bin/csh -f
+#!/bin/bash
+#
+# Top-level script to run hd-us tests
+#
 
-cp ~/ems_us/main/model/hd/shoc .
-cp ~/ems_us/main/model/hd-us/compas .
+# Build list of test directories
+TESTDIRS=("closed")
+LEN=${#TESTDIRS[@]}
+
+ARG=""
+if [ $# -gt 0 ]; then
+    ARG=$1
+fi
+
+COMPAS=../../hd-us/compas
+if [ ! -f $COMPAS ];then
+    echo "COMPAS executable ($COMPAS) not found, skipping ...."
+    exit -1
+fi
+
+echo "---------------------------"
+echo "Found ${LEN} tests in hd-us"
+echo "---------------------------"
+p=0
+exit_status=0
+for (( i=0; i<LEN; i++ )); do
+    dname=${TESTDIRS[$i]}
+    cd ${dname}
+    echo "Running $dname ..."
+    # cat README.md
+    ./run_${dname}
+    # Check exit status
+    if [ $? -ne 0 ]; then
+	echo -e "FAILED ${dname}\n"
+	exit_status=1
+    else
+	echo -e "PASSED ${dname}\n"
+	((p=p+1))
+    fi
+    cd ..
+done
+
+echo "#############################"
+echo "PASSED $p out of ${LEN} tests"
+echo "#############################"
+
+# Format table for internal dev
+if [ "${ARG}" = "cronicle" ];then
+    read -r -d '' VAR << EOM
+{
+   "html": {
+      "title": "Run results",
+      "content": "<h1>Passed $p out of ${LEN} tests</h1>",
+      "caption": "Run results, see below for any errors"
+   }
+}
+EOM
+echo $VAR
+fi
+
+exit $exit_status
 
 echo "Running test2/closed..."
 cd test2/closed
